version: '3.4'

#Dev config file for docker-compose

services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-vetelib_api}
      - MYSQL_USER=${MYSQL_USER:-vetelib}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-!ChangeMe!}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secretR00tPassw0rd}
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - symfony_api
    env_file:
      - .env
  
  php:
    build:
      context: .
      target: vetelib_php
    volumes:
      - .:/srv/api:rw
      - ./docker/php/conf.d/dev.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
    networks:
      - symfony_api
    env_file:
      - .env

  nginx:
    build:
      context: .
      target: vetelib_nginx  
    volumes:
      - ./public:/srv/api/public:ro
    depends_on:
      - php
    ports:
      - 8080:80
    networks:
      - symfony_api

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

volumes:
  database_data:

networks:
  symfony_api: