version: '3.4'

services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-vetelib_api}
      - MYSQL_USER=${MYSQL_USER:-vetelib}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-!ChangeMe!}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secretR00tPassw0rd}
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - symfony_api
    expose:
      - 3306
    env_file:
      - .env
  
  php:
    image: ${PHP_IMAGE}:${APP_VERSION}
    restart: always
    environment:
      - APP_DEBUG=${APP_DEBUG:-0}
      - APP_ENV=${APP_ENV:-prod}
      - APP_SECRET=${APP_SECRET:?APP_SECRET is undefined}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN:?CORS_ALLOW_ORIGIN is undefined}
      - DATABASE_URL=${DATABASE_URL:?DATABASE_URL is undefined}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:?TRUSTED_HOSTS is undefined}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-"10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"}
    depends_on:
      - db
    networks:
      - symfony_api
    env_file:
      - .env

  nginx:
    image: ${NGINX_IMAGE}:${APP_VERSION}
    restart: always
    depends_on:
      - php
    ports:
      - 8080:80
    networks:
      - symfony_api

volumes:
  database_data:

networks:
  symfony_api: